// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @title LAWP Shared Structures and Enums
/// @author Obinna Franklin Duru (BinnaDev)
/// @notice Defines the core data structures used across the Libertas Alpha Water Project.
/// @dev Designed with strict struct packing for gas-efficient state storage.
library LAWPStructs {
    /// @notice Defines the permissible outbound financial flows (Strict Flow Whitelisting invariant).
    enum FlowType {
        RoC, // Return of Contribution (capped exactly at net principal)
        GRANT_INITIAL, // System 1: 30/50/20 split (Activator Sale)
        GRANT_CONTINUOUS // System 2: 10/55/25/10 split (Continuous Refill)
    }

    /// @notice Tracks the exact fractional equity and RoC state of a contributor.
    /// @dev Uses uint256 to prevent intermediate math overflows during proportional yield calculations.
    struct TokenData {
        uint256 netPrincipal; // Net CNGN locked after the 7-10% risk fee deduction
        uint256 rocReturned; // Amount of principal already returned (capped at netPrincipal)
        uint256 poolShareBPS; // Fractional ownership in Basis Points (e.g., 2000 = 20%)
        uint256 poolId; // Identifier for the specific deployment pool (e.g., FUTO campus)
    }

    /// @notice Gas-optimized proposal structure for the Multi-Sig payload.
    /// @dev Tightly packed into a single 256-bit storage slot to minimize execution costs.
    /// Layout: uint96 (12 bytes) + enum (1 byte) + bool (1 byte) + uint40 (5 bytes) = 19 bytes packed into 1 slot.
    struct Proposal {
        uint96 totalRevenue; // Total CNGN generated by the real-world activity
        FlowType flowType; // Classification of the revenue flow
        bool executed; // Execution state flag to prevent double-spending
        uint40 submittedAt; // Timestamp of proposal submission
    }
}
